### PR TITLE
chore: remove redundant client

### PR DESCRIPTION
**Pull request by parthea**
deletes erroneous client [google/dataflow_v1beta3](https://github.com/googleapis/python-dataflow-client/tree/master/google/dataflow_v1beta3) which is not being updated

### CODE REVIEW

**Comment by busunkim96** [comment]
Is this a case where API calls made to v1beta3 never worked?

**Comment by parthea** [comment]
This is a different issue. This is deleting an obsolete client located [here](https://github.com/googleapis/python-dataflow-client/tree/master/google/dataflow_v1beta3). The correct location is [here](https://github.com/googleapis/python-dataflow-client/tree/master/google/cloud/dataflow_v1beta3).

**Comment by busunkim96** [comment]
Ah okay makes sense.

**Review by busunkim96 — APPROVED** [review]

**Comment by busunkim96** [comment]
Thinking about this a bit more, shouldn't it be merged as a `fix`? I'm assuming `from google import dataflow` or `from google import dataflow_v1beta3` worked, so it'd be nice to call it out in the changelog.

**Pull request merged**
